"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var zhMessages = {
  "chart.combotext": "图表名称",
  "editpopup.cancel": "取消",
  "editpopup.deletefeature": "删除",
  "editpopup.deletefeaturetitle": "删除选中的要素",
  "editpopup.deletemsg": "删除要素时出现问题",
  "editpopup.errormsg": "保存要素到服务器时出错. {msg}",
  "editpopup.layer": "指定到图层",
  "editpopup.save": "保存",
  "editpopup.savetitle": "保存编辑的属性",
  "editpopup.updatemsg": "更新要素属性时出错.",
  "infopopup.nametext": "名称",
  "infopopup.nofeatures": "没有选中要素",
  "infopopup.nulltext": "空",
  "infopopup.valuetext": "值",
  "zoom.zoomintitle": "放大",
  "zoom.zoomouttitle": "缩小",
  "labelmodal.applybutton": "应用",
  "labelmodal.clearbutton": "清除",
  "labelmodal.closebutton": "关闭",
  "labelmodal.title": "{layer}图层的标注",
  "layerlist.layertitle": "图层",
  "layerlist.draglayerlabel": "移动图层",
  "layerlist.downloadbuttonlabel": "下载图层",
  "layerlist.filterbuttonlabel": "图层筛选",
  "drawfeature.dropdowntitle": "画图形",
  "drawfeature.linestring": "画线",
  "drawfeature.point": "画点",
  "drawfeature.polygon": "画多边形",
  "select.clearselectiontext": "清除选择",
  "select.menubuttontext": "选择",
  "select.menubuttontitle": "通过矩形选择",
  "select.selectbyrectangletext": "画矩形选择",
  "navigation.buttontitle": "切换到地图操作 (平移和缩放)",
  "querybuilder.addbuttontext": "添加",
  "querybuilder.addbuttontitle": "添加到当前选择",
  "querybuilder.clearbuttontext": "清空",
  "querybuilder.clearbuttontitle": "清空当前选择",
  "querybuilder.countmsg": "{count, plural, =0 {没有要素} 一个 {# 要素} 其它 {# 要素}} 与筛选条件相符.",
  "querybuilder.errortext": "错误的筛选条件, 例如应该是 属性名 == \"属性值\"",
  "querybuilder.filterbuttontext": "通过给定条件筛选到的要素",
  "querybuilder.filterlabel": "筛选条件",
  "querybuilder.layerlabel": "图层",
  "querybuilder.newbuttontext": "新建",
  "querybuilder.newbuttontitle": "新建选择",
  "querybuilder.selectintext": "改选",
  "querybuilder.selectintitle": "改选到最新选择",
  "layerselector.emptytext": "选择一个图层",
  "layerselector.labeltext": "图层",
  "filleditor.filllabel": "填充",
  "filtereditor.addfilter": "添加筛选条件",
  "filtereditor.attributelabel": "属性",
  "filtereditor.emptytext": "选择一个属性",
  "filtereditor.errortext": "错误的筛选条件, 例如可以使用 属性名 == \"属性值\"",
  "filtereditor.filterlabel": "条件筛选",
  "filtereditor.filterplaceholder": "输入筛选表达式 ....",
  "filterhelp.example1description": "人口数量大于10000的所有地块",
  "filterhelp.example1filter": "人口数量 > 10000",
  "filterhelp.example2description": "马坊村的所有集体地",
  "filterhelp.example2filter": "村 == \"马坊村\" and 土地类型 == \"集体地\")",
  "filterhelp.exampletext": "例子:",
  "filterhelp.generalsection": "表达式可以包含属性名称、字符、数字和数学符号。 属性名称需要被单引号(\')包含以避免歧义. 字符需要被双引号 (\")包含.数字和数学符号不需要引号.",
  "filterhelp.introtextprefix": "输入",
  "filterhelp.introtextsuffix": "一个条件筛选表达式来控制查询一个或多个属性。",
  "filterhelp.operator1": "a == b",
  "filterhelp.operator10": "e or f",
  "filterhelp.operator10description": "符合e或f任意一个表达式 ",
  "filterhelp.operator11": "not e",
  "filterhelp.operator11description": "返回所有不满足表达式e的结果",
  "filterhelp.operator1description": "a 等于 b",
  "filterhelp.operator2": "a != b",
  "filterhelp.operator2description": "a 不等于 b",
  "filterhelp.operator3": "a < a",
  "filterhelp.operator3description": "a 小于 b",
  "filterhelp.operator4": "a <= b",
  "filterhelp.operator4description": "a 小于或者等于 b",
  "filterhelp.operator5": "a > b",
  "filterhelp.operator5description": "a 大于 b",
  "filterhelp.operator6": "a >= b",
  "filterhelp.operator6description": "a 大于或者等于 b",
  "filterhelp.operator7": "a like b",
  "filterhelp.operator7description": "a包含b (大小写不敏感)",
  "filterhelp.operator8": "a in (x,y,z)",
  "filterhelp.operator8description": "a等于括号中列出的一个值 x,y,z",
  "filterhelp.operator9": "e and f",
  "filterhelp.operator9description": "同时符合e和f两个表达式",
  "filterhelp.operatortext": "支持的运算有:",
  "filterhelp.parantheses": "任意表达式用圆括号括起来会更清楚 (例如同时使用and和or条件).",
  "filtermodal.addfiltertext": "添加",
  "filtermodal.closebutton": "取消",
  "filtermodal.errortext": "错误的筛选条件, 例如可以使用 属性名 == \"属性值\"",
  "filtermodal.inputlabel": "条件筛选",
  "filtermodal.title": "从 {layer} 图层筛选",
  "featuretable.clearbuttontext": "清除",
  "featuretable.clearbuttontitle": "清除选择",
  "featuretable.deletemsg": "删除要素时出现问题.",
  "featuretable.errormsg": "筛选要素时出现错误. ({msg})",
  "featuretable.filterbuttontext": "通过给定条件筛选到的结果",
  "featuretable.filterhelptext": "属性名 == \"属性值\"",
  "featuretable.filterlabel": "条件筛选",
  "featuretable.filterplaceholder": "输入筛选表达式",
  "featuretable.layerlabel": "图层",
  "featuretable.loaderrormsg": "加载要素时出现错误. ({msg})",
  "featuretable.onlyselected": "只显示选中的要素",
  "featuretable.optionslabel": "选项",
  "featuretable.zoombuttontext": "缩放",
  "featuretable.zoombuttontitle": "缩放到选中的要素",
  "geocoding.placeholder": "搜索地址...",
  "geocodingresults.noresults": "没有找到结果",
  "homebutton.buttontitle": "缩放到初始范围",
  "imageexport.buttontext": "导出成图片",
  "imageexport.buttontitle": "导出成图片",
  "login.buttontext": "系统登陆",
  "login.logouttext": "退出系统",
  "loginmodal.errormsg": "与服务器通信出现故障: {details}",
  "loginmodal.invalidcredentialsmsg": "验证错误",
  "loginmodal.loginbutton": "登陆",
  "loginmodal.passwordlabel": "密码",
  "loginmodal.title": "登陆",
  "loginmodal.userlabel": "用户名",
  "measure.cleartext": "清除",
  "measure.dropdowntext": "测量",
  "measure.dropdowntitle": "在地图上测量距离和面积",
  "measure.measureareatext": "面积",
  "measure.measuredistancetext": "距离",
  "qgisprint.closebuttontext": "关闭",
  "qgisprint.error": "生成PDF文件时出错: {details}",
  "qgisprint.modaltitle": "打印地图",
  "qgisprint.printbuttontext": "打印",
  "qgisprint.printbuttontitle": "打印地图",
  "qgisprint.printmenutext": "打印地图成PDF",
  "qgisprint.resolutionlabel": "分辨率",
};
exports.default = zhMessages;
